### ISSUE TITLE
Phrases dans le formulaire d'une activité à modifier : partie photo/illustration

### ISSUE THREAD

**Issue by SophiePicNat** [picardie-nature/clicnat-sorties-v1#15]
Dans le titre « Photos / Illustration »
> Enlever "s" à "Photos"
> Ajouter la phrase par « Proposez-nous une photo qui permettra d'illustrer les supports de communication en lien avec votre activité. Pour cela merci de nommer votre photo comme cet exemple : sortie_coccinelles_AlbertDupont : cela signifie que je propose une photo pour ma sortie coccinelles et que cette photo a été réalisée par Alebert Dupont ».

**Comment by ndamiens** [comment]
Le nom du fichier n'est pas conservé par Clicnat
