### ISSUE TITLE
Phrases dans le formulaire d'une activité à modifier : partie choix de date et inscription

### ISSUE THREAD

**Issue by SophiePicNat** [picardie-nature/clicnat-sorties-v1#17]
Le texte actuel est : 
"Inscription préalable  
Date limite d'inscription :  
Nombre de participants max :  
0" 

Peut-on avoir les compléments suivants : 
"Si inscription préalable, cochez cette case :  (ou alors une case oui et une case non)
Si oui, indiquez date limite d'inscription :  
Si oui, indiquez le nombre de participants max :  "

**Comment by ndamiens** [comment]
c'est fait
