### ISSUE TITLE
Envoi d'un mail après saisie d'une sortie

### ISSUE THREAD

**Issue by ndamiens** [picardie-nature/clicnat-sorties-v1#2]
Quand un utilisateur propose une sortie clicnat doit envoyer un mail a decouverte@picardie-nature.org pour notifier de cette proposition d’activité

**Comment by SophiePicNat** [comment]
l'alerte doit être mise en place pour 2 cas : 1/ une création d'une nouvelle activité  2/ pour une création d'une nouvelle date pour une activité déjà existante dans le formulaire.

**Comment by ndamiens** [comment]
ça colle pas pile poil parce qu'il n'y aura pas de mail envoyé à la création de la sortie, car elle n'a pas encore d'info de saisie au moment de sa création. Et après envoyer un mail à chaque modification je pense que ça va devenir lourd dingue.

là il envoi un mail à chaque ajout de date
