### ISSUE TITLE
2 Issues closed mais non visibles en ligne :  [clicnat-sorties-v1] Phrases dans le formulaire d'une activité à modifier : partie description activité, champs "structure" (#18) + partie description activité, champs "contact" (#19)

### ISSUE THREAD

**Issue by SophiePicNat** [picardie-nature/clicnat-sorties-v1#21]
Trop contente de voir les issues se réaliser, je suis allée voir sur le site, mais le formulaire n'a pas changé. Peut être une question d'actualisation ? à voir?
 merci !!

**Comment by ndamiens** [comment]
Effectivement, il y a toujours un delta entre moment où je met là modif sur github et celuioù je fais la mise à jour du serveur
